### PR TITLE
Msg handling

### PR DESCRIPTION
**Pull request by felix0908**
Not sure if fully incorporated in original code, but the extract part itself definitely works!
Yet to test mixed zip-and-msg files, like emails with zip attachments or zips with msgs inside of them, but no reason to think it wouldn't work

### CODE REVIEW

**Comment by felix0908** [comment]
Have since tested mails and zips mixed with each other, and it works

**Comment by felix0908** [comment]
Someone might wanna test our master unarchiver to see if it handles nested archive files correctly in its current incarnation - because this branch didn't with those changes!

**Comment by felix0908** [comment]
Made this a draft so no one merges it in yet, thereby overwriting the changes made to unarchiver (that were merged into this branch and then undone manually)

**Comment by felix0908** [comment]
Someone might wanna test our master unarchiver to see if it handles nested archive files correctly in its current incarnation - because this branch didn't with those changes!

**Review by clausjuhl — APPROVED** [review]

**Pull request merged**
